name: Run Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22.0.1'
          distribution: 'temurin'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: List test resources
        run: ls -R src/test/resources

      - name: Create report directories
        run: |
          mkdir -p target/cucumber-reports/html
          mkdir -p target/cucumber-reports/json
          mkdir -p target/cucumber-reports/xml
          mkdir -p target/extent-cucumber-report

      - name: Run Tests
        run: mvn clean test

      - name: List generated reports
        run: ls -R target

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/cucumber-reports/html/**
            target/cucumber-reports/json/**
            target/cucumber-reports/xml/**
            target/extent-cucumber-report/**
            target/surefire-reports/**
            target/cucumber-reports.html
            target/extent-cucumber-report.html

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        with:
          name: test-recordings
          path: recordings/
